2024-11-28 16:25:19,336 - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-28 16:25:20,641 - config - INFO - Логирование инициализировано. Логи сохраняются в файл: logs.log
2024-11-28 16:25:20,641 - config - INFO - Время отправки отчетов операторам установлено на 18:00
2024-11-28 16:25:20,641 - config - INFO - Конфигурация загружена успешно за 0.00 секунд.
2024-11-28 16:25:20 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:25:20 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:25:20 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:25:21 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:25:21 - [КРОТ] - KROT - INFO - Бот успешно запущен.
2024-11-28 16:25:21 - [КРОТ] - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:25:21 - [КРОТ] - KROT - INFO - Настройка HTTPXRequest...
2024-11-28 16:25:21,318 - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:25:21,318 - KROT - INFO - Настройка HTTPXRequest...
2024-11-28 16:25:21 - [КРОТ] - KROT - INFO - Настройка приложения Telegram...
2024-11-28 16:25:21,324 - KROT - INFO - Настройка приложения Telegram...
2024-11-28 16:25:21 - [КРОТ] - KROT - INFO - Запуск бота...
2024-11-28 16:25:21,332 - KROT - INFO - Запуск бота...
2024-11-28 16:25:21 - [КРОТ] - KROT - INFO - Успешное подключение к базе данных.
2024-11-28 16:25:21 - [КРОТ] - KROT - INFO - Обработчики команд настроены.
2024-11-28 16:25:21,709 - KROT - INFO - Успешное подключение к базе данных.
2024-11-28 16:25:21,710 - KROT - INFO - Обработчики команд настроены.
2024-11-28 16:25:21 - [КРОТ] - KROT - INFO - Бот успешно инициализирован.
2024-11-28 16:25:21,718 - KROT - INFO - Бот успешно инициализирован.
2024-11-28 16:25:40 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3493 сек)
2024-11-28 16:25:40,909 - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3493 сек)
2024-11-28 16:25:41 - [КРОТ] - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2271 сек).
2024-11-28 16:25:41,136 - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2271 сек).
2024-11-28 16:25:41 - [КРОТ] - KROT - INFO - Команды установлены для роли: Developer
2024-11-28 16:25:41,619 - KROT - INFO - Команды установлены для роли: Developer
2024-11-28 16:25:41 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-28 16:25:41,897 - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-28 16:25:42 - [КРОТ] - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 16:25:42,593 - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 16:25:42 - [КРОТ] - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-28 16:25:42 - [КРОТ] - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 16:25:42,598 - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-28 16:25:42 - [КРОТ] - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 16:25:42,598 - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 16:25:42,599 - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 16:25:44 - [КРОТ] - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 16:25:44,769 - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 16:27:07 - [КРОТ] - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-28 16:27:07,285 - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-28 16:27:08,234 - config - INFO - Логирование инициализировано. Логи сохраняются в файл: logs.log
2024-11-28 16:27:08,234 - config - INFO - Время отправки отчетов операторам установлено на 18:00
2024-11-28 16:27:08,234 - config - INFO - Конфигурация загружена успешно за 0.00 секунд.
2024-11-28 16:27:08 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:27:08 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:27:08 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:27:08 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:27:08 - [КРОТ] - KROT - INFO - Бот успешно запущен.
2024-11-28 16:27:08 - [КРОТ] - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:27:08,908 - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:27:08 - [КРОТ] - KROT - INFO - Настройка HTTPXRequest...
2024-11-28 16:27:08,908 - KROT - INFO - Настройка HTTPXRequest...
2024-11-28 16:27:08 - [КРОТ] - KROT - INFO - Настройка приложения Telegram...
2024-11-28 16:27:08,924 - KROT - INFO - Настройка приложения Telegram...
2024-11-28 16:27:08 - [КРОТ] - KROT - INFO - Запуск бота...
2024-11-28 16:27:08,936 - KROT - INFO - Запуск бота...
2024-11-28 16:27:09 - [КРОТ] - KROT - INFO - Успешное подключение к базе данных.
2024-11-28 16:27:09 - [КРОТ] - KROT - INFO - Обработчики команд настроены.
2024-11-28 16:27:09,331 - KROT - INFO - Успешное подключение к базе данных.
2024-11-28 16:27:09,332 - KROT - INFO - Обработчики команд настроены.
2024-11-28 16:27:09 - [КРОТ] - KROT - INFO - Бот успешно инициализирован.
2024-11-28 16:27:09,338 - KROT - INFO - Бот успешно инициализирован.
2024-11-28 16:27:11 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3364 сек)
2024-11-28 16:27:11,301 - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3364 сек)
2024-11-28 16:27:11 - [КРОТ] - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2186 сек).
2024-11-28 16:27:11,520 - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2186 сек).
2024-11-28 16:27:11 - [КРОТ] - KROT - INFO - Команды установлены для роли: Developer
2024-11-28 16:27:11,641 - KROT - INFO - Команды установлены для роли: Developer
2024-11-28 16:27:11 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-28 16:27:11,754 - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-28 16:27:12 - [КРОТ] - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 16:27:12,601 - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 16:27:12 - [КРОТ] - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-28 16:27:12 - [КРОТ] - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 16:27:12,605 - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-28 16:27:12 - [КРОТ] - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 16:27:12,605 - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 16:27:12,606 - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 16:27:34 - [КРОТ] - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 16:27:34,119 - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 16:30:53 - [КРОТ] - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-28 16:30:53,126 - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-28 16:30:54,310 - config - INFO - Логирование инициализировано. Логи сохраняются в файл: logs.log
2024-11-28 16:30:54,311 - config - INFO - Время отправки отчетов операторам установлено на 18:00
2024-11-28 16:30:54,311 - config - INFO - Конфигурация загружена успешно за 0.00 секунд.
2024-11-28 16:30:54 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:30:54 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:30:54 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:30:54 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:30:54 - [КРОТ] - KROT - INFO - Бот успешно запущен.
2024-11-28 16:30:54 - [КРОТ] - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:30:54 - [КРОТ] - KROT - INFO - Настройка HTTPXRequest...
2024-11-28 16:30:54,919 - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:30:54,919 - KROT - INFO - Настройка HTTPXRequest...
2024-11-28 16:30:54 - [КРОТ] - KROT - INFO - Настройка приложения Telegram...
2024-11-28 16:30:54,926 - KROT - INFO - Настройка приложения Telegram...
2024-11-28 16:30:54 - [КРОТ] - KROT - INFO - Запуск бота...
2024-11-28 16:30:54,933 - KROT - INFO - Запуск бота...
2024-11-28 16:30:55 - [КРОТ] - KROT - INFO - Успешное подключение к базе данных.
2024-11-28 16:30:55 - [КРОТ] - KROT - INFO - Обработчики команд настроены.
2024-11-28 16:30:55,294 - KROT - INFO - Успешное подключение к базе данных.
2024-11-28 16:30:55,295 - KROT - INFO - Обработчики команд настроены.
2024-11-28 16:30:55 - [КРОТ] - KROT - INFO - Бот успешно инициализирован.
2024-11-28 16:30:55,301 - KROT - INFO - Бот успешно инициализирован.
2024-11-28 16:30:59 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3392 сек)
2024-11-28 16:30:59,565 - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3392 сек)
2024-11-28 16:30:59 - [КРОТ] - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2166 сек).
2024-11-28 16:30:59,782 - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2166 сек).
2024-11-28 16:30:59 - [КРОТ] - KROT - INFO - Команды установлены для роли: Developer
2024-11-28 16:30:59,895 - KROT - INFO - Команды установлены для роли: Developer
2024-11-28 16:31:00 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-28 16:31:00,019 - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-28 16:31:02 - [КРОТ] - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 16:31:02,178 - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 16:31:02 - [КРОТ] - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-28 16:31:02 - [КРОТ] - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 16:31:02 - [КРОТ] - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 16:31:02,180 - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-28 16:31:02,181 - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 16:31:02,181 - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 16:31:04 - [КРОТ] - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 16:31:04,323 - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 16:33:34 - [КРОТ] - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-28 16:33:34,157 - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-28 16:33:35,161 - config - INFO - Логирование инициализировано. Логи сохраняются в файл: logs.log
2024-11-28 16:33:35,161 - config - INFO - Время отправки отчетов операторам установлено на 18:00
2024-11-28 16:33:35,161 - config - INFO - Конфигурация загружена успешно за 0.00 секунд.
2024-11-28 16:33:35 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:33:35 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:33:35 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:33:35 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:33:35 - [КРОТ] - KROT - INFO - Бот успешно запущен.
2024-11-28 16:33:35 - [КРОТ] - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:33:35 - [КРОТ] - KROT - INFO - Настройка HTTPXRequest...
2024-11-28 16:33:35,927 - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:33:35,928 - KROT - INFO - Настройка HTTPXRequest...
2024-11-28 16:33:35 - [КРОТ] - KROT - INFO - Настройка приложения Telegram...
2024-11-28 16:33:35,935 - KROT - INFO - Настройка приложения Telegram...
2024-11-28 16:33:35 - [КРОТ] - KROT - INFO - Запуск бота...
2024-11-28 16:33:35,943 - KROT - INFO - Запуск бота...
2024-11-28 16:33:36 - [КРОТ] - KROT - INFO - Успешное подключение к базе данных.
2024-11-28 16:33:36 - [КРОТ] - KROT - INFO - Обработчики команд настроены.
2024-11-28 16:33:36,314 - KROT - INFO - Успешное подключение к базе данных.
2024-11-28 16:33:36,315 - KROT - INFO - Обработчики команд настроены.
2024-11-28 16:33:36 - [КРОТ] - KROT - INFO - Бот успешно инициализирован.
2024-11-28 16:33:36,321 - KROT - INFO - Бот успешно инициализирован.
2024-11-28 16:33:38 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3370 сек)
2024-11-28 16:33:38,327 - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3370 сек)
2024-11-28 16:33:38 - [КРОТ] - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2225 сек).
2024-11-28 16:33:38,549 - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2225 сек).
2024-11-28 16:33:38 - [КРОТ] - KROT - INFO - Команды установлены для роли: Developer
2024-11-28 16:33:38,636 - KROT - INFO - Команды установлены для роли: Developer
2024-11-28 16:33:38 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-28 16:33:38,767 - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-28 16:33:39 - [КРОТ] - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 16:33:39,563 - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 16:33:39 - [КРОТ] - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-28 16:33:39 - [КРОТ] - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 16:33:39 - [КРОТ] - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 16:33:39,566 - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-28 16:33:39,567 - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 16:33:39,567 - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 16:33:41 - [КРОТ] - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 16:33:41,534 - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 16:35:16 - [КРОТ] - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-28 16:35:16,530 - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-28 16:35:17,525 - config - INFO - Логирование инициализировано. Логи сохраняются в файл: logs.log
2024-11-28 16:35:17,525 - config - INFO - Время отправки отчетов операторам установлено на 18:00
2024-11-28 16:35:17,525 - config - INFO - Конфигурация загружена успешно за 0.00 секунд.
2024-11-28 16:35:17 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:35:17 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:35:17 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:35:18 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:35:18 - [КРОТ] - KROT - INFO - Бот успешно запущен.
2024-11-28 16:35:18 - [КРОТ] - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:35:18 - [КРОТ] - KROT - INFO - Настройка HTTPXRequest...
2024-11-28 16:35:18,150 - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:35:18,150 - KROT - INFO - Настройка HTTPXRequest...
2024-11-28 16:35:18 - [КРОТ] - KROT - INFO - Настройка приложения Telegram...
2024-11-28 16:35:18,157 - KROT - INFO - Настройка приложения Telegram...
2024-11-28 16:35:18 - [КРОТ] - KROT - INFO - Запуск бота...
2024-11-28 16:35:18,163 - KROT - INFO - Запуск бота...
2024-11-28 16:35:18 - [КРОТ] - KROT - INFO - Успешное подключение к базе данных.
2024-11-28 16:35:18,519 - KROT - INFO - Успешное подключение к базе данных.
2024-11-28 16:35:18 - [КРОТ] - KROT - INFO - Обработчики команд настроены.
2024-11-28 16:35:18,519 - KROT - INFO - Обработчики команд настроены.
2024-11-28 16:35:18 - [КРОТ] - KROT - INFO - Бот успешно инициализирован.
2024-11-28 16:35:18,523 - KROT - INFO - Бот успешно инициализирован.
2024-11-28 16:35:22 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3288 сек)
2024-11-28 16:35:22,043 - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3288 сек)
2024-11-28 16:35:22 - [КРОТ] - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2173 сек).
2024-11-28 16:35:22,261 - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2173 сек).
2024-11-28 16:35:22 - [КРОТ] - KROT - INFO - Команды установлены для роли: Developer
2024-11-28 16:35:22,364 - KROT - INFO - Команды установлены для роли: Developer
2024-11-28 16:35:22 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-28 16:35:22,472 - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-28 16:35:23 - [КРОТ] - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 16:35:23,217 - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 16:35:23 - [КРОТ] - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-28 16:35:23,225 - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-28 16:35:23 - [КРОТ] - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 16:35:23 - [КРОТ] - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 16:35:23,225 - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 16:35:23,225 - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 16:36:28 - [КРОТ] - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 16:36:28,458 - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 16:40:04 - [КРОТ] - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-28 16:40:04,077 - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-28 16:40:05,849 - config - INFO - Логирование инициализировано. Логи сохраняются в файл: logs.log
2024-11-28 16:40:05,849 - config - INFO - Время отправки отчетов операторам установлено на 18:00
2024-11-28 16:40:05,849 - config - INFO - Конфигурация загружена успешно за 0.00 секунд.
2024-11-28 16:40:06 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:40:06 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:40:06 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:40:06 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:40:06 - [КРОТ] - KROT - INFO - Бот успешно запущен.
2024-11-28 16:40:06 - [КРОТ] - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:40:06 - [КРОТ] - KROT - INFO - Настройка HTTPXRequest...
2024-11-28 16:40:06,503 - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 16:40:06,503 - KROT - INFO - Настройка HTTPXRequest...
2024-11-28 16:40:06 - [КРОТ] - KROT - INFO - Настройка приложения Telegram...
2024-11-28 16:40:06,511 - KROT - INFO - Настройка приложения Telegram...
2024-11-28 16:40:06 - [КРОТ] - KROT - INFO - Запуск бота...
2024-11-28 16:40:06,521 - KROT - INFO - Запуск бота...
2024-11-28 16:40:06 - [КРОТ] - KROT - INFO - Успешное подключение к базе данных.
2024-11-28 16:40:06,896 - KROT - INFO - Успешное подключение к базе данных.
2024-11-28 16:40:06 - [КРОТ] - KROT - INFO - Обработчики команд настроены.
2024-11-28 16:40:06,897 - KROT - INFO - Обработчики команд настроены.
2024-11-28 16:40:06 - [КРОТ] - KROT - INFO - Бот успешно инициализирован.
2024-11-28 16:40:06,904 - KROT - INFO - Бот успешно инициализирован.
2024-11-28 16:40:12 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3501 сек)
2024-11-28 16:40:12,274 - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3501 сек)
2024-11-28 16:40:12 - [КРОТ] - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2201 сек).
2024-11-28 16:40:12,495 - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2201 сек).
2024-11-28 16:40:12 - [КРОТ] - KROT - INFO - Команды установлены для роли: Developer
2024-11-28 16:40:12,792 - KROT - INFO - Команды установлены для роли: Developer
2024-11-28 16:40:12 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-28 16:40:12,916 - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-28 16:40:13 - [КРОТ] - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 16:40:13,336 - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 16:40:13 - [КРОТ] - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-28 16:40:13,339 - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-28 16:40:13 - [КРОТ] - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 16:40:13 - [КРОТ] - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 16:40:13,340 - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 16:40:13,340 - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 16:41:20 - [КРОТ] - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 16:41:20,528 - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 16:45:15 - [КРОТ] - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 16:45:15,508 - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 16:45:15 - [КРОТ] - KROT - INFO - Кастомный диапазон дат: 2024-11-18 - 2024-11-18
2024-11-28 16:45:15 - [КРОТ] - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 16:45:15,533 - KROT - INFO - Кастомный диапазон дат: 2024-11-18 - 2024-11-18
2024-11-28 16:45:15,533 - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 16:45:15 - [КРОТ] - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 16:45:15,534 - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 16:46:13 - [КРОТ] - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 16:46:13,297 - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 17:17:58 - [КРОТ] - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-28 17:17:58,684 - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-28 17:17:59,884 - config - INFO - Логирование инициализировано. Логи сохраняются в файл: logs.log
2024-11-28 17:17:59,885 - config - INFO - Время отправки отчетов операторам установлено на 18:00
2024-11-28 17:17:59,885 - config - INFO - Конфигурация загружена успешно за 0.00 секунд.
2024-11-28 17:18:00 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 17:18:00 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 17:18:00 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 17:18:00 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 17:18:00 - [КРОТ] - KROT - INFO - Бот успешно запущен.
2024-11-28 17:18:00 - [КРОТ] - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 17:18:00 - [КРОТ] - KROT - INFO - Настройка HTTPXRequest...
2024-11-28 17:18:00,550 - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-28 17:18:00,550 - KROT - INFO - Настройка HTTPXRequest...
2024-11-28 17:18:00 - [КРОТ] - KROT - INFO - Настройка приложения Telegram...
2024-11-28 17:18:00,556 - KROT - INFO - Настройка приложения Telegram...
2024-11-28 17:18:00 - [КРОТ] - KROT - INFO - Запуск бота...
2024-11-28 17:18:00,564 - KROT - INFO - Запуск бота...
2024-11-28 17:18:01 - [КРОТ] - KROT - INFO - Успешное подключение к базе данных.
2024-11-28 17:18:01 - [КРОТ] - KROT - INFO - Обработчики команд настроены.
2024-11-28 17:18:01,176 - KROT - INFO - Успешное подключение к базе данных.
2024-11-28 17:18:01,178 - KROT - INFO - Обработчики команд настроены.
2024-11-28 17:18:01 - [КРОТ] - KROT - INFO - Бот успешно инициализирован.
2024-11-28 17:18:01,189 - KROT - INFO - Бот успешно инициализирован.
2024-11-28 17:18:20 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3376 сек)
2024-11-28 17:18:20,142 - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3376 сек)
2024-11-28 17:18:20 - [КРОТ] - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2169 сек).
2024-11-28 17:18:20,360 - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2169 сек).
2024-11-28 17:18:20 - [КРОТ] - KROT - INFO - Команды установлены для роли: Developer
2024-11-28 17:18:20,729 - KROT - INFO - Команды установлены для роли: Developer
2024-11-28 17:18:21 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-28 17:18:21,010 - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-28 17:18:21 - [КРОТ] - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 17:18:21,859 - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-28 17:18:21 - [КРОТ] - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-28 17:18:21 - [КРОТ] - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 17:18:21,863 - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-28 17:18:21 - [КРОТ] - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 17:18:21,864 - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-28 17:18:21,864 - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-28 17:19:30 - [КРОТ] - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-28 17:19:30,148 - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-29 12:05:37,342 - config - INFO - Логирование инициализировано. Логи сохраняются в файл: logs.log
2024-11-29 12:05:37,342 - config - INFO - Время отправки отчетов операторам установлено на 18:00
2024-11-29 12:05:37,342 - config - INFO - Конфигурация загружена успешно за 0.00 секунд.
2024-11-29 12:05:37 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:05:37 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:05:37 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:05:38 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:05:38 - [КРОТ] - KROT - INFO - Бот успешно запущен.
2024-11-29 12:05:38 - [КРОТ] - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:05:38 - [КРОТ] - KROT - INFO - Настройка HTTPXRequest...
2024-11-29 12:05:38,213 - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:05:38,213 - KROT - INFO - Настройка HTTPXRequest...
2024-11-29 12:05:38 - [КРОТ] - KROT - INFO - Настройка приложения Telegram...
2024-11-29 12:05:38,228 - KROT - INFO - Настройка приложения Telegram...
2024-11-29 12:05:38 - [КРОТ] - KROT - INFO - Запуск бота...
2024-11-29 12:05:38,236 - KROT - INFO - Запуск бота...
2024-11-29 12:05:38 - [КРОТ] - KROT - INFO - Успешное подключение к базе данных.
2024-11-29 12:05:38,935 - KROT - INFO - Успешное подключение к базе данных.
2024-11-29 12:05:38 - [КРОТ] - KROT - INFO - Обработчики команд настроены.
2024-11-29 12:05:38,936 - KROT - INFO - Обработчики команд настроены.
2024-11-29 12:05:38 - [КРОТ] - KROT - INFO - Бот успешно инициализирован.
2024-11-29 12:05:38,957 - KROT - INFO - Бот успешно инициализирован.
2024-11-29 12:05:56 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3588 сек)
2024-11-29 12:05:56,908 - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3588 сек)
2024-11-29 12:05:57 - [КРОТ] - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2339 сек).
2024-11-29 12:05:57,143 - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2339 сек).
2024-11-29 12:05:57 - [КРОТ] - KROT - INFO - Команды установлены для роли: Developer
2024-11-29 12:05:57,434 - KROT - INFO - Команды установлены для роли: Developer
2024-11-29 12:05:57 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-29 12:05:57,585 - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-29 12:05:58 - [КРОТ] - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-29 12:05:58,382 - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-29 12:05:58 - [КРОТ] - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-29 12:05:58 - [КРОТ] - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-29 12:05:58,388 - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-29 12:05:58 - [КРОТ] - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-29 12:05:58,388 - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-29 12:05:58,389 - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-29 12:06:00 - [КРОТ] - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-29 12:06:00,601 - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-29 12:09:25 - [КРОТ] - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-29 12:09:25,490 - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-29 12:09:26,812 - config - INFO - Логирование инициализировано. Логи сохраняются в файл: logs.log
2024-11-29 12:09:26,812 - config - INFO - Время отправки отчетов операторам установлено на 18:00
2024-11-29 12:09:26,812 - config - INFO - Конфигурация загружена успешно за 0.00 секунд.
2024-11-29 12:09:27 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:09:27 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:09:27 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:09:27 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:09:27 - [КРОТ] - KROT - INFO - Бот успешно запущен.
2024-11-29 12:09:27 - [КРОТ] - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:09:27 - [КРОТ] - KROT - INFO - Настройка HTTPXRequest...
2024-11-29 12:09:27,550 - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:09:27,550 - KROT - INFO - Настройка HTTPXRequest...
2024-11-29 12:09:27 - [КРОТ] - KROT - INFO - Настройка приложения Telegram...
2024-11-29 12:09:27,557 - KROT - INFO - Настройка приложения Telegram...
2024-11-29 12:09:27 - [КРОТ] - KROT - INFO - Запуск бота...
2024-11-29 12:09:27,566 - KROT - INFO - Запуск бота...
2024-11-29 12:09:27 - [КРОТ] - KROT - INFO - Успешное подключение к базе данных.
2024-11-29 12:09:27 - [КРОТ] - KROT - INFO - Обработчики команд настроены.
2024-11-29 12:09:27,952 - KROT - INFO - Успешное подключение к базе данных.
2024-11-29 12:09:27,953 - KROT - INFO - Обработчики команд настроены.
2024-11-29 12:09:27 - [КРОТ] - KROT - INFO - Бот успешно инициализирован.
2024-11-29 12:09:27,960 - KROT - INFO - Бот успешно инициализирован.
2024-11-29 12:09:30 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3542 сек)
2024-11-29 12:09:30,895 - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3542 сек)
2024-11-29 12:09:31 - [КРОТ] - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2412 сек).
2024-11-29 12:09:31,137 - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2412 сек).
2024-11-29 12:09:31 - [КРОТ] - KROT - INFO - Команды установлены для роли: Developer
2024-11-29 12:09:31,270 - KROT - INFO - Команды установлены для роли: Developer
2024-11-29 12:09:31 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-29 12:09:31,484 - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-29 12:09:32 - [КРОТ] - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-29 12:09:32,434 - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-29 12:09:32 - [КРОТ] - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-29 12:09:32 - [КРОТ] - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-29 12:09:32,437 - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-29 12:09:32 - [КРОТ] - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-29 12:09:32,438 - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-29 12:09:32,438 - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-29 12:09:34 - [КРОТ] - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-29 12:09:34,462 - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-29 12:16:32 - [КРОТ] - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-29 12:16:32,846 - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-29 12:16:34,071 - config - INFO - Логирование инициализировано. Логи сохраняются в файл: logs.log
2024-11-29 12:16:34,071 - config - INFO - Время отправки отчетов операторам установлено на 18:00
2024-11-29 12:16:34,071 - config - INFO - Конфигурация загружена успешно за 0.00 секунд.
2024-11-29 12:16:34 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:16:34 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:16:34 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:16:35 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:16:35 - [КРОТ] - KROT - INFO - Бот успешно запущен.
2024-11-29 12:16:35 - [КРОТ] - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:16:35 - [КРОТ] - KROT - INFO - Настройка HTTPXRequest...
2024-11-29 12:16:35,481 - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:16:35,481 - KROT - INFO - Настройка HTTPXRequest...
2024-11-29 12:16:35 - [КРОТ] - KROT - INFO - Настройка приложения Telegram...
2024-11-29 12:16:35,489 - KROT - INFO - Настройка приложения Telegram...
2024-11-29 12:16:35 - [КРОТ] - KROT - INFO - Запуск бота...
2024-11-29 12:16:35,498 - KROT - INFO - Запуск бота...
2024-11-29 12:16:36 - [КРОТ] - KROT - INFO - Успешное подключение к базе данных.
2024-11-29 12:16:36,219 - KROT - INFO - Успешное подключение к базе данных.
2024-11-29 12:16:36 - [КРОТ] - KROT - INFO - Обработчики команд настроены.
2024-11-29 12:16:36,219 - KROT - INFO - Обработчики команд настроены.
2024-11-29 12:16:36 - [КРОТ] - KROT - INFO - Бот успешно инициализирован.
2024-11-29 12:16:36,224 - KROT - INFO - Бот успешно инициализирован.
2024-11-29 12:16:43 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3660 сек)
2024-11-29 12:16:43,245 - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3660 сек)
2024-11-29 12:16:43 - [КРОТ] - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2408 сек).
2024-11-29 12:16:43,486 - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2408 сек).
2024-11-29 12:16:43 - [КРОТ] - KROT - INFO - Команды установлены для роли: Developer
2024-11-29 12:16:43,787 - KROT - INFO - Команды установлены для роли: Developer
2024-11-29 12:16:43 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-29 12:16:43,914 - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-29 12:16:45 - [КРОТ] - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-29 12:16:45,043 - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-29 12:16:45 - [КРОТ] - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-29 12:16:45 - [КРОТ] - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-29 12:16:45 - [КРОТ] - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-29 12:16:45,048 - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-29 12:16:45,049 - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-29 12:16:45,049 - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-29 12:16:47 - [КРОТ] - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-29 12:16:47,364 - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-29 12:35:03 - [КРОТ] - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-29 12:35:03,064 - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-29 12:35:05,407 - config - INFO - Логирование инициализировано. Логи сохраняются в файл: logs.log
2024-11-29 12:35:05,407 - config - INFO - Время отправки отчетов операторам установлено на 18:00
2024-11-29 12:35:05,408 - config - INFO - Конфигурация загружена успешно за 0.00 секунд.
2024-11-29 12:35:05 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:35:05 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:35:05 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:35:06 - [КРОТ] - KROT - INFO - [КРОТ]: Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:35:06 - [КРОТ] - KROT - INFO - Бот успешно запущен.
2024-11-29 12:35:06 - [КРОТ] - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:35:06 - [КРОТ] - KROT - INFO - Настройка HTTPXRequest...
2024-11-29 12:35:06,158 - KROT - INFO - Логирование настроено. Логи сохраняются в файл: logs.log
2024-11-29 12:35:06,158 - KROT - INFO - Настройка HTTPXRequest...
2024-11-29 12:35:06 - [КРОТ] - KROT - INFO - Настройка приложения Telegram...
2024-11-29 12:35:06,173 - KROT - INFO - Настройка приложения Telegram...
2024-11-29 12:35:06 - [КРОТ] - KROT - INFO - Запуск бота...
2024-11-29 12:35:06,196 - KROT - INFO - Запуск бота...
2024-11-29 12:35:06 - [КРОТ] - KROT - INFO - Успешное подключение к базе данных.
2024-11-29 12:35:06 - [КРОТ] - KROT - INFO - Обработчики команд настроены.
2024-11-29 12:35:06,638 - KROT - INFO - Успешное подключение к базе данных.
2024-11-29 12:35:06,639 - KROT - INFO - Обработчики команд настроены.
2024-11-29 12:35:06 - [КРОТ] - KROT - INFO - Бот успешно инициализирован.
2024-11-29 12:35:06,644 - KROT - INFO - Бот успешно инициализирован.
2024-11-29 12:35:34 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3961 сек)
2024-11-29 12:35:34,867 - KROT - INFO - Пользователь 309606681 успешно аутентифицирован как {'role_name': 'Developer'}. (Время выполнения: 0.3961 сек)
2024-11-29 12:35:35 - [КРОТ] - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2417 сек).
2024-11-29 12:35:35,110 - KROT - INFO - [КРОТ]: Роль пользователя с ID '309606681' успешно получена: Developer (Время выполнения: 0.2417 сек).
2024-11-29 12:35:35 - [КРОТ] - KROT - INFO - Команды установлены для роли: Developer
2024-11-29 12:35:35,492 - KROT - INFO - Команды установлены для роли: Developer
2024-11-29 12:35:35 - [КРОТ] - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-29 12:35:35,740 - KROT - INFO - Пользователь 309606681 успешно вошел в систему с ролью {'role_name': 'Developer'}.
2024-11-29 12:35:36 - [КРОТ] - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-29 12:35:36,102 - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-29 12:35:36 - [КРОТ] - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-29 12:35:36 - [КРОТ] - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-29 12:35:36,109 - KROT - INFO - Кастомный диапазон дат: 2024-11-11 - 2024-11-17
2024-11-29 12:35:36 - [КРОТ] - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-29 12:35:36,113 - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-29 12:35:36,120 - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-29 12:35:57 - [КРОТ] - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-29 12:35:57,159 - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-29 12:46:08 - [КРОТ] - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-29 12:46:08 - [КРОТ] - KROT - INFO - Кастомный диапазон дат: 2024-10-01 - 2024-11-25
2024-11-29 12:46:08 - [КРОТ] - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-29 12:46:08,663 - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-29 12:46:08 - [КРОТ] - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-29 12:46:08,666 - KROT - INFO - Кастомный диапазон дат: 2024-10-01 - 2024-11-25
2024-11-29 12:46:08,667 - KROT - INFO - Начата генерация отчета для пользователя 8 за период 'custom'.
2024-11-29 12:46:08,670 - KROT - INFO - Запрос на генерацию отчета для user_id 8 с периодом custom
2024-11-29 12:46:29 - [КРОТ] - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-29 12:46:29,299 - KROT - INFO - Отчет для пользователя 8 успешно сгенерирован и отправлен.
2024-11-29 12:47:14 - [КРОТ] - KROT - INFO - Команда /start получена от пользователя 309606681
2024-11-29 12:47:14,894 - KROT - INFO - Команда /start получена от пользователя 309606681
2024-11-29 12:47:42 - [КРОТ] - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-29 12:47:42 - [КРОТ] - KROT - INFO - Кастомный диапазон дат: 2024-10-01 - 2024-11-25
2024-11-29 12:47:42,692 - KROT - INFO - Команда /generate_report получена от пользователя 309606681
2024-11-29 12:47:42 - [КРОТ] - KROT - INFO - Начата генерация отчета для пользователя 5 за период 'custom'.
2024-11-29 12:47:42,695 - KROT - INFO - Кастомный диапазон дат: 2024-10-01 - 2024-11-25
2024-11-29 12:47:42,696 - KROT - INFO - Начата генерация отчета для пользователя 5 за период 'custom'.
2024-11-29 12:47:42 - [КРОТ] - KROT - INFO - Запрос на генерацию отчета для user_id 5 с периодом custom
2024-11-29 12:47:42,697 - KROT - INFO - Запрос на генерацию отчета для user_id 5 с периодом custom
2024-11-29 12:48:03 - [КРОТ] - KROT - INFO - Отчет для пользователя 5 успешно сгенерирован и отправлен.
2024-11-29 12:48:03,575 - KROT - INFO - Отчет для пользователя 5 успешно сгенерирован и отправлен.
2024-11-29 13:30:00 - [КРОТ] - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
2024-11-29 13:30:00,380 - KROT - ERROR - Необработанное исключение
Traceback (most recent call last):
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 959, in <module>
    asyncio.run(main())
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/opt/anaconda3/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 957, in main
    await bot.run()
  File "/Users/vitalyefimov/Projects/operabot/bot.py", line 349, in run
    await self.application.run_polling()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 881, in run_polling
    return self.__run(
           ^^^^^^^^^^^
  File "/Users/vitalyefimov/Projects/operabot/venv/lib/python3.11/site-packages/telegram/ext/_application.py", line 1109, in __run
    loop.close()
  File "/opt/anaconda3/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/opt/anaconda3/lib/python3.11/asyncio/selector_events.py", line 88, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
